---
title: "Pronosticar Acopio Nacional"
output: html_notebook
---
# Setup Librerias y Directorio
```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = "G:/Mi unidad/casos_uso_analitica/fomento_ganadero/pronostico_leche_cruda")
```
```{r}
library(tidyverse)
library(lubridate)
library(tidymodels)
library(modeltime)
library(DBI)
library(RSQLite)
```

# Cargar Modelo
```{r}
modelo_pronostico_acopio_formal <- readRDS(file = "artifacts/modelo_pronostico_acopio_nacional.rds")
```

# Importar Datos
## Datos Acopio
```{r}
config <- configr::read.config(file = "config/config.json")

con <- dbConnect(drv = SQLite(),paste0('data/',config$config_base$base_datos))


nacional_acopio_leche <- 
  dbReadTable(conn = con, name = "recoleccion_nacional_leche") %>% 
  mutate(fecha = as.Date(fecha),
         anio = lubridate::year(fecha),
         mes = lubridate::month(fecha))
dbDisconnect(con)
#rm(con, config)
```

## Agrupa Datos Acopio Formal Nacional
```{r}
acopio_formal <- 
nacional_acopio_leche %>% 
  dplyr::filter(fecha >= as.Date("2010-01-01") ) %>% 
  group_by(fecha) %>% 
  summarise(precio_promedio_acopio_formal = weighted.mean(x = precio, w = volumen_recoleccion),
            litros_acopio_formal = sum(volumen_recoleccion)) %>% 
  ungroup()
```
### Grafica Acopio Formal
```{r}
acopio_formal %>% 
  ggplot(aes(x = fecha, y = litros_acopio_formal ))+
  geom_line(color = "navy")+
  scale_x_date(name = "Fecha", date_breaks = "1 year", date_labels = "%Y")+
  scale_y_continuous(name = "Millones de litros", 
                     limits = c(1.5e8, 3.25e8),
                     labels = scales::label_comma(scale = 1/1e6),
                     n.breaks = 10)+
  ggtitle(label = "Acopio Formal Leche", subtitle = "Fuente: Min Agricultura - USP")+
  theme_bw()+
  theme( panel.grid.minor = element_blank())
```

# Pronosticar Acopio Formal

```{r}
 modelo_pronostico_acopio_formal_refit<- modelo_pronostico_acopio_formal %>% 
  modeltime_refit(data = acopio_formal) 
```
```{r}
forecast_acopio_formal <- modelo_pronostico_acopio_formal_refit %>% 
  modeltime_forecast(h=13, new_data = acopio_formal, actual_data = acopio_formal)

```

```{r}
colores <- c("actual" = "navy", "prediction" = "darkgreen")

forecast_acopio_formal %>% 
  dplyr::filter(.index >= as.Date("2021-01-01")) %>% 
ggplot(aes(x = .index, y = .value, color = .key))+
  geom_line()+
  geom_point()+
  geom_vline(xintercept = seq.Date(from = as.Date("2021-01-01"), to = as.Date("2024-01-01"), by = "1 year"), color = "gray")+
  scale_x_date(name = "Fecha", date_breaks = "1 month", date_labels = "%Y-%b")+
  scale_y_continuous(name = "Millones de litros", 
                     limits = c(2.25e8, 3.25e8),
                     labels = scales::label_comma(scale = 1/1e6),
                     n.breaks = 10)+
  scale_color_manual(values = colores)+
  ggtitle(label = "Acopio Formal Leche", subtitle = "Fuente: Min Agricultura - USP")+
  theme_bw()+
  theme( panel.grid.minor = element_blank(), 
         axis.text.x = element_text(angle = 90, vjust = 0.5),
         legend.title = element_blank())
```
```{r}
nombre_archivo_resultados <- paste0("results/pronostico_Acopio_Formal_", Sys.Date(), ".txt")

forecast_acopio_formal %>% 
  dplyr::filter(.key =="prediction") %>% 
write_excel_csv2(file =nombre_archivo_resultados)
```

